update
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils

install findutils
install bash
install zsh

install wget --enable-iri
install vim --override-system-vi
tap homebrew/dupes
install homebrew/dupes/grep
install the_silver_searcher
install git
install node

install python

cleanup
doctor
